---
# Site-Specific configuration file

project_name: Project Name
project_machine_name: project_name
project_url: project-url.com

# Custom Logo for Dashboard
dashboard:
  logo: "images/dvm-logo-{{ project_machine_name }}.png"
  favicon: "images/favicon.ico"

# Alias Info

alias:
  root_path: "/var/www/vhosts/vml/{{ project_url }}/htdocs"
  files_path: "/sites/default/files"
  local:
    name: "local"
    links: []
#      - "{{ stash }}"
#      - "{{ jira }}"
#      - "{{ prod_site }}"
#  dev:
#    name: "dev"
#    uri: "dev.{{ project_machine_name }}.com"
#    host: "dev.proxy"
#    links:
#      - "{{ jenkins.dev }}"
#  stage:
#    name: "stage"
#    uri: "stage.{{ project_machine_name }}.com"
#    host: "stage.proxy"
#    links:
#      - "{{ jenkins.stage }}"
#  prod:
#    name: "prod"
#    uri: "{{ project_url }}"
#    host: "prod.proxy"
#    links:
#      - "{{ jenkins.prod }}"

# Project Source Links

# Jenkins
jenkins_base_url: "https://jenkins-server.com/job/{{ project_url }}"
jenkins:
  dev:
    title: "Jenkins"
    path: "{{ jenkins_base_url }}-dev"
  stage:
    title: "Jenkins"
    path: "{{ jenkins_base_url }}-stage"
  prod:
    title: "Jenkins"
    path: "{{ jenkins_base_url }}-prod"

# Stash
stash:
  title: "Stash Repo"
  path: "https://stash-server.com/projects/{{ ssh_username }}/repos/{{ project_url }}/browse"

# Jira
jira_project_alias: "JIRA"
jira:
  title: "Jira Board"
  path: "https://jira-server.com/projects/{{ jira_project_alias }}"

# Production
prod_site:
  title: "{{ project_name }}"
  path: "https://{{ project_url }}"
